name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install helm
      run: sudo apt install helm
    - name: Print out directory
      run: ls -al

