name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install helm
      run: sudo curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - name: Lint helm chart
      run: helm lint
      working-directory: ./k8s/example
    - name: Package Helm chart
      run: helm package example
      working-directory: ./k8s
    - name: Add Artifactory repository
      run: helm repo add helm https://tbctdevops.jfrog.io/tbctdevops/helm --username ${{ secrets.artifactory_username }} --password ${{ secrets.artifactory_apikey}}
    - name: Add helm chart to Artifactory repository
      run: curl -H 'X-JFrog-Art-Api:${{ secrets.artifactory_apikey }}' -T example-0.1.0.tgz "https://tbctdevops.jfrog.io/tbctdevops/helm/"
      working-directory: ./k8s

